# Generated by Django 2.2.6 on 2019-10-22 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_fan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fan',
            new_name='fans',
        ),
    ]
