# Generated by Django 2.2.6 on 2019-10-22 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posting',
            old_name='user',
            new_name='author',
        ),
    ]
