# Generated by Django 2.2.6 on 2019-10-22 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0002_auto_20191022_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='hashtags',
        ),
        migrations.RemoveField(
            model_name='posting',
            name='like_users',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='HashTag',
        ),
    ]
